"""
anomaly.py — Anomaly detection engine for Awake session metrics.

Parses AWAKE_LOG.md and detects unusual patterns across sessions:
  - Sudden test count drops
  - Complexity spikes (high lines-added : tests-added ratio)
  - Session velocity changes (time between sessions)
  - Missing metrics in session entries
  - PR count anomalies (unusually high or low)

Uses IQR-based outlier detection — no ML dependencies, pure stdlib.

Public API
----------
detect_anomalies(repo_path, log_path=None) -> AnomalyReport
"""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class Anomaly:
    """A single detected anomaly in session metrics."""

    severity: str          # "INFO", "WARNING", "CRITICAL"
    session: int           # session number where the anomaly was detected
    kind: str              # short machine-readable type tag
    description: str       # human-readable explanation
    metric_name: str       # which metric triggered the anomaly
    metric_value: float    # the anomalous value
    expected_range: str    # e.g. "12.0 – 48.0"
    suggested_action: str  # what to do about it

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class AnomalyReport:
    """Full anomaly detection report across all sessions."""

    sessions_analyzed: int
    total_anomalies: int
    critical_count: int
    warning_count: int
    info_count: int
    anomalies: list        # list[Anomaly]

    def to_dict(self) -> dict:
        return {
            "sessions_analyzed": self.sessions_analyzed,
            "total_anomalies": self.total_anomalies,
            "critical_count": self.critical_count,
            "warning_count": self.warning_count,
            "info_count": self.info_count,
            "anomalies": [a.to_dict() for a in self.anomalies],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    def to_markdown(self) -> str:
        lines: list[str] = []
        lines.append("# Awake: Anomaly Detection Report")
        lines.append("")
        lines.append(
            "> *An AI monitoring its own development metrics — "
            "because the system that builds itself should also watch itself.*"
        )
        lines.append("")
        lines.append("---")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Sessions analyzed | {self.sessions_analyzed} |")
        lines.append(f"| Total anomalies | {self.total_anomalies} |")
        lines.append(f"| Critical | {self.critical_count} |")
        lines.append(f"| Warning | {self.warning_count} |")
        lines.append(f"| Info | {self.info_count} |")
        lines.append("")

        if not self.anomalies:
            lines.append("*No anomalies detected. All metrics within expected ranges.*")
            lines.append("")
        else:
            # Group by severity
            for sev in ("CRITICAL", "WARNING", "INFO"):
                group = [a for a in self.anomalies if a.severity == sev]
                if not group:
                    continue
                icon = {"CRITICAL": "[!!]", "WARNING": "[!]", "INFO": "[i]"}[sev]
                lines.append(f"## {icon} {sev} ({len(group)})")
                lines.append("")
                for a in group:
                    lines.append(f"### Session {a.session}: {a.kind}")
                    lines.append("")
                    lines.append(a.description)
                    lines.append("")
                    lines.append(f"- **Metric:** {a.metric_name} = {a.metric_value}")
                    lines.append(f"- **Expected range:** {a.expected_range}")
                    lines.append(f"- **Action:** {a.suggested_action}")
                    lines.append("")

        lines.append("---")
        lines.append("")
        lines.append(
            "*Generated by `awake anomalies` — "
            "the AI that builds itself now monitors itself.*"
        )
        lines.append("")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# AWAKE_LOG.md parser (reuse patterns from insights.py)
# ---------------------------------------------------------------------------

_RE_SESSION_HEADER = re.compile(
    r"^##\s+Session\s+(\d+)\s*--\s*(.+?)\s*\((\d{4}-\d{2}-\d{2})\)",
    re.MULTILINE,
)
_RE_STAT_MODULES = re.compile(
    r"\|\s*Source modules\s*\|\s*([\d,]+)\s*\|", re.IGNORECASE
)
_RE_STAT_TESTS = re.compile(
    r"\|\s*Tests\s*\|\s*([\d,~]+\+?)\s*\|", re.IGNORECASE
)
_RE_STAT_PRS = re.compile(
    r"\|\s*PRs opened\s*\|\s*([\d,]+)\s*\|", re.IGNORECASE
)
_RE_STAT_LINES = re.compile(
    r"\|\s*Lines added\s*\|\s*~?([\d,]+)\s*\|", re.IGNORECASE
)
_RE_STAT_TESTS_PASSING = re.compile(
    r"\|\s*Tests\s*(?:\(local\))?\s*\|\s*([\d,]+)\s*passed", re.IGNORECASE
)
_RE_PR_LINE = re.compile(r"^\s*[-*]\s*PR\s*#(\d+)", re.MULTILINE)


@dataclass
class _SessionData:
    """Internal parsed record with raw metrics."""

    number: int
    date: str
    title: str
    prs: int
    modules: int          # cumulative source modules (0 if not reported)
    tests: int            # cumulative test count (0 if not reported)
    lines_added: int      # lines added this session (0 if not reported)
    has_modules_stat: bool
    has_tests_stat: bool
    has_prs_stat: bool
    has_lines_stat: bool


def _parse_int(text: str) -> int:
    cleaned = re.sub(r"[,~+]", "", text.strip())
    try:
        return int(cleaned)
    except ValueError:
        return 0


def _parse_log(log_text: str) -> list[_SessionData]:
    """Parse AWAKE_LOG.md into session data records."""
    session_matches = list(_RE_SESSION_HEADER.finditer(log_text))
    if not session_matches:
        return []

    records: list[_SessionData] = []
    for idx, match in enumerate(session_matches):
        start = match.start()
        end = (
            session_matches[idx + 1].start()
            if idx + 1 < len(session_matches)
            else len(log_text)
        )
        chunk = log_text[start:end]

        session_num = int(match.group(1))
        session_date = match.group(3).strip()
        session_title = match.group(2).strip()

        modules_match = _RE_STAT_MODULES.search(chunk)
        tests_match = _RE_STAT_TESTS.search(chunk)
        prs_stat_match = _RE_STAT_PRS.search(chunk)
        lines_match = _RE_STAT_LINES.search(chunk)
        tests_passing = _RE_STAT_TESTS_PASSING.search(chunk)

        cumulative_modules = _parse_int(modules_match.group(1)) if modules_match else 0
        cumulative_tests = _parse_int(tests_match.group(1)) if tests_match else 0
        if not cumulative_tests and tests_passing:
            cumulative_tests = _parse_int(tests_passing.group(1))
        lines_added = _parse_int(lines_match.group(1)) if lines_match else 0

        if prs_stat_match:
            pr_count = _parse_int(prs_stat_match.group(1))
        else:
            pr_count = len(_RE_PR_LINE.findall(chunk))

        records.append(_SessionData(
            number=session_num,
            date=session_date,
            title=session_title,
            prs=pr_count,
            modules=cumulative_modules,
            tests=cumulative_tests,
            lines_added=lines_added,
            has_modules_stat=modules_match is not None,
            has_tests_stat=(tests_match is not None or tests_passing is not None),
            has_prs_stat=prs_stat_match is not None,
            has_lines_stat=lines_match is not None,
        ))

    return sorted(records, key=lambda r: r.number)


# ---------------------------------------------------------------------------
# Statistical helpers
# ---------------------------------------------------------------------------


def _iqr_bounds(values: list[float], k: float = 1.5) -> tuple[float, float]:
    """Compute IQR-based lower/upper bounds for outlier detection.

    Returns (lower_bound, upper_bound).  Values outside these bounds
    are considered outliers.
    """
    if len(values) < 4:
        if not values:
            return (0.0, 0.0)
        return (min(values), max(values))

    s = sorted(values)
    n = len(s)
    q1 = s[n // 4]
    q3 = s[(3 * n) // 4]
    iqr = q3 - q1
    return (q1 - k * iqr, q3 + k * iqr)


def _mean(values: list[float]) -> float:
    if not values:
        return 0.0
    return sum(values) / len(values)


def _stdev(values: list[float]) -> float:
    if len(values) < 2:
        return 0.0
    m = _mean(values)
    return math.sqrt(sum((v - m) ** 2 for v in values) / (len(values) - 1))


def _z_score(value: float, mean: float, stdev: float) -> float:
    if stdev == 0:
        return 0.0
    return (value - mean) / stdev


# ---------------------------------------------------------------------------
# Anomaly detectors
# ---------------------------------------------------------------------------


def _detect_test_drops(records: list[_SessionData]) -> list[Anomaly]:
    """Detect sessions where cumulative test count decreased."""
    anomalies: list[Anomaly] = []
    prev_tests = 0
    for rec in records:
        if rec.tests > 0:
            if prev_tests > 0 and rec.tests < prev_tests:
                drop = prev_tests - rec.tests
                anomalies.append(Anomaly(
                    severity="CRITICAL",
                    session=rec.number,
                    kind="test_count_drop",
                    description=(
                        f"Test count dropped from {prev_tests} to {rec.tests} "
                        f"(lost {drop} tests). Tests should only increase across "
                        f"sessions unless a module was intentionally removed."
                    ),
                    metric_name="cumulative_tests",
                    metric_value=float(rec.tests),
                    expected_range=f">= {prev_tests}",
                    suggested_action=(
                        "Investigate whether tests were deleted intentionally. "
                        "Check git diff for removed test files."
                    ),
                ))
            prev_tests = rec.tests
    return anomalies


def _detect_complexity_spikes(records: list[_SessionData]) -> list[Anomaly]:
    """Detect sessions with disproportionately many lines vs tests added."""
    anomalies: list[Anomaly] = []

    # Compute per-session test deltas
    prev_tests = 0
    session_ratios: list[tuple[_SessionData, float]] = []
    for rec in records:
        tests_added = max(0, rec.tests - prev_tests) if rec.tests > 0 else 0
        if rec.lines_added > 0 and tests_added > 0:
            ratio = rec.lines_added / tests_added
            session_ratios.append((rec, ratio))
        elif rec.lines_added > 100 and tests_added == 0:
            # Lots of lines with zero tests is always suspicious
            anomalies.append(Anomaly(
                severity="WARNING",
                session=rec.number,
                kind="complexity_spike",
                description=(
                    f"Session {rec.number} added ~{rec.lines_added} lines "
                    f"but reported 0 new tests. This may indicate untested code "
                    f"was introduced."
                ),
                metric_name="lines_per_test",
                metric_value=float(rec.lines_added),
                expected_range="lines/tests ratio < 50",
                suggested_action=(
                    "Review the code added in this session for test coverage gaps."
                ),
            ))
        if rec.tests > 0:
            prev_tests = rec.tests

    if len(session_ratios) >= 3:
        ratios = [r for _, r in session_ratios]
        lo, hi = _iqr_bounds(ratios)
        for rec, ratio in session_ratios:
            if ratio > hi and ratio > 50:
                anomalies.append(Anomaly(
                    severity="WARNING",
                    session=rec.number,
                    kind="complexity_spike",
                    description=(
                        f"Session {rec.number} had a lines-to-tests ratio of "
                        f"{ratio:.1f} (added ~{rec.lines_added} lines for "
                        f"{int(rec.lines_added / ratio)} new tests). "
                        f"This is above the IQR upper bound of {hi:.1f}."
                    ),
                    metric_name="lines_per_test",
                    metric_value=round(ratio, 1),
                    expected_range=f"{lo:.1f} – {hi:.1f}",
                    suggested_action=(
                        "Check if the lines added are boilerplate, data, or "
                        "generated code that doesn't need proportional tests."
                    ),
                ))

    return anomalies


def _detect_velocity_changes(records: list[_SessionData]) -> list[Anomaly]:
    """Detect dramatic changes in time between sessions."""
    anomalies: list[Anomaly] = []

    if len(records) < 3:
        return anomalies

    # Compute gaps in days between consecutive sessions
    gaps: list[tuple[_SessionData, float]] = []
    for i in range(1, len(records)):
        try:
            d1 = datetime.strptime(records[i - 1].date, "%Y-%m-%d")
            d2 = datetime.strptime(records[i].date, "%Y-%m-%d")
            gap_days = (d2 - d1).days
            gaps.append((records[i], float(gap_days)))
        except ValueError:
            continue

    if len(gaps) < 3:
        return anomalies

    gap_values = [g for _, g in gaps]
    lo, hi = _iqr_bounds(gap_values)
    m = _mean(gap_values)
    sd = _stdev(gap_values)

    for rec, gap in gaps:
        z = _z_score(gap, m, sd)
        if gap > hi and abs(z) > 2.0 and gap > 3:
            anomalies.append(Anomaly(
                severity="INFO",
                session=rec.number,
                kind="velocity_gap",
                description=(
                    f"Session {rec.number} came {int(gap)} days after the "
                    f"previous session — significantly longer than the average "
                    f"gap of {m:.1f} days (z-score: {z:.1f})."
                ),
                metric_name="days_since_previous",
                metric_value=gap,
                expected_range=f"{max(0, lo):.1f} – {hi:.1f} days",
                suggested_action=(
                    "Consider whether external factors caused the gap. "
                    "Long gaps may indicate blocked dependencies or priority shifts."
                ),
            ))
        elif gap < lo and abs(z) > 2.0 and gap < 0:
            # Negative gap would mean date ordering issues
            anomalies.append(Anomaly(
                severity="WARNING",
                session=rec.number,
                kind="date_ordering_issue",
                description=(
                    f"Session {rec.number} appears to have a date "
                    f"before the previous session ({gap} days gap). "
                    f"This may indicate a logging error."
                ),
                metric_name="days_since_previous",
                metric_value=gap,
                expected_range=f">= 0 days",
                suggested_action="Check AWAKE_LOG.md dates for this session.",
            ))

    # Also detect burst: many sessions on same day
    from collections import Counter
    date_counts = Counter(r.date for r in records)
    for date, count in date_counts.items():
        if count >= 4:
            burst_sessions = [r.number for r in records if r.date == date]
            anomalies.append(Anomaly(
                severity="INFO",
                session=burst_sessions[0],
                kind="session_burst",
                description=(
                    f"{count} sessions ran on {date} "
                    f"(sessions {', '.join(str(s) for s in burst_sessions)}). "
                    f"This is a marathon build day — unusual even for an AI."
                ),
                metric_name="sessions_per_day",
                metric_value=float(count),
                expected_range="1 – 3 sessions per day",
                suggested_action=(
                    "Verify all sessions completed successfully. "
                    "Marathon days increase risk of accumulated errors."
                ),
            ))

    return anomalies


def _detect_missing_metrics(records: list[_SessionData]) -> list[Anomaly]:
    """Detect sessions with missing expected stats fields."""
    anomalies: list[Anomaly] = []

    for rec in records:
        missing: list[str] = []
        if not rec.has_prs_stat and rec.prs == 0:
            missing.append("PRs opened")
        if not rec.has_tests_stat:
            missing.append("Tests")
        if not rec.has_modules_stat:
            missing.append("Source modules")

        if len(missing) >= 2:
            anomalies.append(Anomaly(
                severity="WARNING",
                session=rec.number,
                kind="missing_metrics",
                description=(
                    f"Session {rec.number} is missing {len(missing)} expected "
                    f"stats fields: {', '.join(missing)}. Incomplete entries "
                    f"reduce the accuracy of trend analysis."
                ),
                metric_name="missing_fields",
                metric_value=float(len(missing)),
                expected_range="0 missing fields",
                suggested_action=(
                    "Update the AWAKE_LOG.md entry for this session with "
                    "the missing stats."
                ),
            ))
        elif len(missing) == 1:
            anomalies.append(Anomaly(
                severity="INFO",
                session=rec.number,
                kind="missing_metrics",
                description=(
                    f"Session {rec.number} is missing the '{missing[0]}' "
                    f"stat field."
                ),
                metric_name="missing_fields",
                metric_value=1.0,
                expected_range="0 missing fields",
                suggested_action=(
                    f"Add the {missing[0]} stat to this session's log entry."
                ),
            ))

    return anomalies


def _detect_pr_anomalies(records: list[_SessionData]) -> list[Anomaly]:
    """Detect unusually high or low PR counts."""
    anomalies: list[Anomaly] = []

    pr_counts = [float(r.prs) for r in records if r.prs > 0]
    if len(pr_counts) < 3:
        return anomalies

    lo, hi = _iqr_bounds(pr_counts)
    m = _mean(pr_counts)
    sd = _stdev(pr_counts)

    for rec in records:
        if rec.prs == 0:
            continue  # handled by missing_metrics
        z = _z_score(float(rec.prs), m, sd)
        if rec.prs > hi and abs(z) > 2.0:
            anomalies.append(Anomaly(
                severity="INFO",
                session=rec.number,
                kind="pr_count_high",
                description=(
                    f"Session {rec.number} opened {rec.prs} PRs — "
                    f"significantly above the average of {m:.1f} "
                    f"(z-score: {z:.1f}). This was an exceptionally "
                    f"productive session."
                ),
                metric_name="prs_opened",
                metric_value=float(rec.prs),
                expected_range=f"{max(0, lo):.1f} – {hi:.1f}",
                suggested_action=(
                    "No action needed — high PR count indicates a burst of "
                    "productivity. Verify all PRs passed CI."
                ),
            ))

    return anomalies


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def detect_anomalies(
    repo_path: Path,
    log_path: Optional[Path] = None,
) -> AnomalyReport:
    """Parse AWAKE_LOG.md and detect anomalies in session metrics.

    Args:
        repo_path: Root of the Awake repository.
        log_path:  Explicit path to the log file. If None, defaults to
                   ``repo_path / "AWAKE_LOG.md"``.

    Returns:
        AnomalyReport with all detected anomalies.
    """
    if log_path is None:
        log_path = repo_path / "AWAKE_LOG.md"

    log_text = ""
    if log_path.exists():
        log_text = log_path.read_text(encoding="utf-8")

    records = _parse_log(log_text)

    if not records:
        return AnomalyReport(
            sessions_analyzed=0,
            total_anomalies=0,
            critical_count=0,
            warning_count=0,
            info_count=0,
            anomalies=[],
        )

    # Run all detectors
    all_anomalies: list[Anomaly] = []
    all_anomalies.extend(_detect_test_drops(records))
    all_anomalies.extend(_detect_complexity_spikes(records))
    all_anomalies.extend(_detect_velocity_changes(records))
    all_anomalies.extend(_detect_missing_metrics(records))
    all_anomalies.extend(_detect_pr_anomalies(records))

    # Sort: CRITICAL first, then WARNING, then INFO; within severity by session
    severity_order = {"CRITICAL": 0, "WARNING": 1, "INFO": 2}
    all_anomalies.sort(key=lambda a: (severity_order.get(a.severity, 9), a.session))

    critical = sum(1 for a in all_anomalies if a.severity == "CRITICAL")
    warning = sum(1 for a in all_anomalies if a.severity == "WARNING")
    info = sum(1 for a in all_anomalies if a.severity == "INFO")

    return AnomalyReport(
        sessions_analyzed=len(records),
        total_anomalies=len(all_anomalies),
        critical_count=critical,
        warning_count=warning,
        info_count=info,
        anomalies=all_anomalies,
    )


# ---------------------------------------------------------------------------
# Entry point (standalone)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    repo = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    report = detect_anomalies(repo)
    print(report.to_markdown())
